### ISSUE TITLE
Requirement of /var/run/ volume

### ISSUE THREAD

**Issue by toonsevrin** [Snyk/fluentd-logzio-kubernetes#2]
Received this error when trying to start:

```
events.js:161
throw er; // Unhandled 'error' event
^
Error: connect ENOENT /var/run/docker.sock
at Object.exports._errnoException (util.js:1023:11)
at exports._exceptionWithHostPort (util.js:1046:20)
at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1090:14)
```

after mounting /var/run/ to the container it worked. This seems not to be documented?

**Comment by adrukh** [comment]
Not sure why this is the case, I have this working fine without an explicit mount. GKE k8s 1.7.3 in my case, maybe your case differs?

**Comment by toonsevrin** [comment]
No idea..
